services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app/backend
      - ./utils:/app/utils
      - ./backend/db:/app/backend/db
      - ./backend/storage:/app/backend/storage
      - ./llama/models:/app/llama/models
      - ./download_model.sh:/app/download_model.sh
    env_file:
      - .env
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Prevents local node_modules from overwriting container
    depends_on:
      - backend